import { MigrationInterface, QueryRunner } from "typeorm";
import { Cast } from "../entities/Cast";
import { CastType } from "@iba-cast-gallery/types";

/**
 * キャストの初期データを挿入するマイグレーション(4/12まで)
 */
export class InsertCasts1744428540129 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {

        await queryRunner.manager.createQueryBuilder()
            .insert()
            .into(Cast)
            .values(casts)
            .execute();
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const idsToDelete = casts.map(p => p.id);
        await queryRunner.manager.createQueryBuilder()
            .delete()
            .from(Cast)
            .where("id IN (:...ids)", { ids: idsToDelete })
            .execute();
    }
}

const casts : Cast[] = [
    {
        id: 1,
        name: 'メノウ',
        enName: 'agate',
        introduceTweetId: '1878744119239209193',
        type: CastType.REAL,
        isActive: true,
        taggedPosts: [],
    },
    {
        id: 2,
        name: 'クジャク',
        enName: 'melachite',
        introduceTweetId: '1879091090134864220',
        type: CastType.REAL,
        isActive: true,
        taggedPosts: [],
    },
    {
        id: 3,
        name: 'ルリ',
        enName: 'lapis-lazuli',
        introduceTweetId: '1879453474661777549',
        type: CastType.REAL,
        isActive: true,
        taggedPosts: [],
    },
    {
        id: 4,
        name: 'スズ',
        enName: 'tin',
        introduceTweetId: '1879815861902647388',
        type: CastType.REAL,
        isActive: true,
        taggedPosts: [],
    },
    {
        id: 5,
        name: 'シンジュ',
        enName: 'pearl',
        introduceTweetId: '1880193349136838830',
        type: CastType.REAL,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:6,
        name: 'コハク',
        enName: 'amber',
        introduceTweetId: '1880540647691587684',
        type: CastType.REAL,
        isActive: true,
        taggedPosts: [],
    },
    {
        id: 7,
        name: "ユウレン",
        enName: "zoisite",
        introduceTweetId: "1880903030205517885",
        type: CastType.REAL,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:8,
        name: 'ヒスイ',
        enName: 'jade',
        introduceTweetId: '1881265418603786573',
        type: CastType.REAL,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:9,
        name: 'ホタル',
        enName: 'florite',
        introduceTweetId: '1881627800299565408',
        type: CastType.REAL,
        isActive: false,
        taggedPosts: [],
    },
    {
        id:10,
        name: 'ザクロ',
        enName: 'garnet',
        introduceTweetId: '1881990198072062114',
        type: CastType.REAL,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:11,
        name: 'リシア',
        enName: 'spodumene',
        introduceTweetId: '1863523515242049540',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:12,
        name: 'マイカ',
        enName: 'mica',
        introduceTweetId: '1863885898036949230',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:13,
        name: 'サファイア',
        enName: 'sapphire',
        introduceTweetId: '1864248285940134212',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:14,
        name: 'テルル',
        enName: 'tellurite',
        introduceTweetId: '1864610677970678102',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:15,
        name: 'ミニアム',
        enName: 'minium',
        introduceTweetId: '1864957970074812418',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:16,
        name: 'ビスマス',
        enName: 'bismuth',
        introduceTweetId: '1865320343021510917',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:17,
        name: 'ラリマー',
        enName: 'larimar',
        introduceTweetId: '1865682737044324518',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:18,
        name: 'シトリン',
        enName: 'citrine',
        introduceTweetId: '1866045128546066870',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:19,
        name: 'スピネル',
        enName: 'spinel',
        introduceTweetId: '1866407506458628516',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:20,
        name:'モリオン',
        enName: 'morion',
        introduceTweetId: '1866769902364729735',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:21,
        name:'ルチル',
        enName: 'rutile',
        introduceTweetId: '1867132291245391919',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:22,
        name:'マーキュリー',
        enName: 'mercury',
        introduceTweetId: '1867494673235030407',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:23,
        name:'スフェーン',
        enName: 'sphene',
        introduceTweetId: '1867857065991180791',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:24,
        name:'レビン',
        enName: 'levyne',
        introduceTweetId: '1868219445488873908',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:25,
        name:'ユナカイト',
        enName: 'unakite',
        introduceTweetId: '1868581846201540798',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:26,
        name:'ネコアイト',
        enName: 'necoite',
        introduceTweetId: '1868944227335626921',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:27,
        name:'フローライト',
        enName: 'fluorite',
        introduceTweetId: '1889257637247869435',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:28,
        name:'クォーツ',
        enName: 'quartzs',
        introduceTweetId: '1889600335628419178',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:29,
        name:'ベリル',
        enName: 'beryl',
        introduceTweetId: '1889962726941929531',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:30,
        name:'タルク',
        enName: 'talc',
        introduceTweetId: '1890325126941380782',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:31,
        name:'オパール',
        enName: 'opal',
        introduceTweetId: '1890687498034053386',
        type: CastType.IMAGINARY,
        isActive: true, 
        taggedPosts: [],
    },
    {
        id:32,
        name:'ガーネット',
        enName: 'garnet',
        introduceTweetId: '1891049886948216908',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:33,
        name:'ネフェリン',
        enName: 'nepheline',
        introduceTweetId: '1891412282145673705',
        type: CastType.IMAGINARY,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:34,
        name:'アラレ',
        enName: 'aragonite',
        introduceTweetId: '1912830902922580054',
        type: CastType.REAL,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:35,
        name:'サンゴ',
        enName: 'coral',
        introduceTweetId: '1911721093628567673',
        type: CastType.REAL,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:36,
        name:'ラン',
        enName: 'vivianite',
        introduceTweetId: '1912083488758792543',
        type: CastType.REAL,
        isActive: true,
        taggedPosts: [],
    },
    {
        id:37,
        name:'ソウ',
        enName: 'bismuhinite',
        introduceTweetId: '1912445864242757802',
        type: CastType.REAL,
        isActive: true,
        taggedPosts: [],
    },
];
